### ISSUE TITLE
How do you add the "bal-app" class to the body?

### ISSUE THREAD

**Issue by gagarine** [baloise/design-system#283]
I do not understand how "bal-app" class is added on body. I'm using vuejs and vite (and no typescript). I read the documentation and the vue-starter-kit code, but this part stay a mystery.

**Comment by hirsch88** [comment]
Hi @gagarine 

The `bal-app` class scopes all our css styles (the global file). 
So without it you will not have access to all our styles, thats why we set that on the body element or any other outer element.

Due to apps, which are running on a CMS page with its own styles we needed to have something to scope it easily.

Cheers,
Gery

**Comment by gagarine** [comment]
Hi @hirsch88, 

I understood the `bal-app` class is necessary. But I do not understand **how** in https://github.com/baloise/vue-starter-kit/tree/vite (the vite version) you did add the class. I could add a wrapper my own way, but I taught perhaps I was missing something their.

Thanks!
Simon

**Comment by hirsch88** [comment]
The `bal-app` class is added in this file => https://github.com/baloise/vue-starter-kit/blob/vite/index.html

**Comment by gagarine** [comment]
Sorry, I just found it (what a stupid mistake) and deleted the question. But you answer it in the same time.

Anyway thanks!
