### ISSUE TITLE
Fix incompatibility with Angular 8

### ISSUE THREAD

**Issue by RudyBricks** [baloise/design-system#58]
Stencil version 1.8.0 and greater use Typescript version 3.7.
Stencil with Typescript version 3.7 is known to generate definition files that are incompatible with Angular 8. It will be supported again only in Angular 9, which in turn is beading edge.

I suggest to downgrade the used stencil version to 1.7.5 until either Angular 9 or a patched Stencil version gets released.

Relevant issue: https://github.com/ionic-team/stencil/issues/2062

**Comment by robinsummerhill** [comment]
> Stencil version 1.8.0 and greater use Typescript version 3.7.
> Stencil with Typescript version 3.7 is known to generate definition files that are incompatible with Angular 8. It will be supported again only in Angular 9, which in turn is beading edge.
> 
> I suggest to downgrade the used stencil version to 1.7.5 until either Angular 9 or a patched Stencil version gets released.
> 
> Relevant issue: [ionic-team/stencil#2062](https://github.com/ionic-team/stencil/issues/2062)

It looks like this issue is not receiving any attention from the Stencil team. I ended up forking the Stencil repo and rolling back the TS3.7 upgrade. This works for now but I notice that the new compiler support is using some of the new features of TS3.7 (e.g. optional chaining) so this will not be an option with 1.8.x versions of Stencil once they switch over to the new compiler.

**Comment by RudyBricks** [comment]
> > Stencil version 1.8.0 and greater use Typescript version 3.7.
> > Stencil with Typescript version 3.7 is known to generate definition files that are incompatible with Angular 8. It will be supported again only in Angular 9, which in turn is beading edge.
> > I suggest to downgrade the used stencil version to 1.7.5 until either Angular 9 or a patched Stencil version gets released.
> > Relevant issue: [ionic-team/stencil#2062](https://github.com/ionic-team/stencil/issues/2062)
> 
> It looks like this issue is not receiving any attention from the Stencil team. I ended up forking the Stencil repo and rolling back the TS3.7 upgrade. This works for now but I notice that the new compiler support is using some of the new features of TS3.7 (e.g. optional chaining) so this will not be an option with 1.8.x versions of Stencil once they switch over to the new compiler.

@robinsummerhill thanks for sharing your previous efforts with TS3.7 and Stencil. It is understandable that the Stelcil team is very busy pushing other issues forward. 

I'm, however, wondering if this could be a reoccurring issue for every typescript minor/major release. Do you think it makes sense to add an abstraction to the compiler support, so that it is able to target arbitrary typescript versions (e.g. through a parameter or other npm-mechanisms)? 
Or in other words, Stencil would use two versions of Typescript: 
- the one that is used by the library itself and is fixed
- the one that is used to generate TS definition files and is configurable somehow

We, of course, could offer support for implementing that

**Comment by robinsummerhill** [comment]
@RCBiczok Now that Angular 9 has been released with Typescript 3.7 support, this issue is less of a problem for us - although other library vendors may still need to support Angular 8.

As for future problems with Typescript updates - I'm hoping that the Typescript team has learned their lesson on introducing breaking changes with no backwards-compatible workaround (and especially not in minor releases). This issue has caused a lot of headaches for many library vendors (not just Stencil/Angular) and I'm sure they have received a lot of grief from developers.

Also - I hope that the Stencil team doesn't jump to new Typescript versions the moment they are released but waits to see if there are problems first.

But I can hope...

Apparently - there is also some work going on to create a tool to convert 3.7 d.ts files to 3.5 d.ts files. This could be included as part of the Stencil build chain when working.
