### ISSUE TITLE
🐛 fix(carousel): card slider with long labels

### ISSUE THREAD

**Issue by hirsch88** [baloise/design-system#711]
### Current Behavior

<img width="367" alt="image" src="https://user-images.githubusercontent.com/6384499/232763897-3b9c07ab-3c53-42c1-9988-4c25de28f4a3.png">

### Expected Behavior

Solutions:

- cut the label with three points ...
- adjust the width to not be equaliy 

the other buttons should have the same height as the biggest

### Steps to Reproduce

-

### Version

12

### Code Reproduction URL

https://baloise-design-system.vercel.app/?path=/story/components-carousel--card-slider&globals=backgrounds.grid:true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
@clastzoo will check the use cases if it is mainly those three labels and provide a design solution

**Comment by clastzoo** [comment]
Component is currently used 15 times – out of this only once for the banking packages. 


![Image](https://github.com/baloise/design-system/assets/62377419/54e7afb9-0a25-4bfd-85f5-169d4d7b6929)
![Image](https://github.com/baloise/design-system/assets/62377419/4b45835b-a4e1-4515-aa00-2506ac5d3ed6)

**Comment by clastzoo** [comment]
@hirsch88 a pragmatic approach would be to decrease the padding to 8px instead of 24px. 
This will solve the issue mostly down to 330px devices.

An alternative approach would be to stack it vertically:

Just a stacking example, design is not approved:
![Image](https://github.com/baloise/design-system/assets/62377419/259b6046-af17-46b1-bbb1-bc2f56f588ec)

Do you agree?
