### ISSUE TITLE
♿️  a11y(bal-radio, bal-checkbox, bal-select): Key Board Navigation

### ISSUE THREAD

**Issue by GinaBiondo** [baloise/design-system#947]
### Current Behavior

Selects, Radios, Checkboxes and Radio and Checkbox Groups need to be checked and refactored for keyboard usage as described [here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/radiogroup_role) and [here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listbox_role).
Check focus state as well.

### Expected Behavior

see above

### Steps to Reproduce

regular usage and keyboard navigation

### Version

13.4.4

### Browsers

Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
@GinaBiondo-aperto can you tells a bit more what accessibility features are requested?

**Comment by hirsch88** [comment]
Check focus with tab on safari

**Comment by mmarinkov** [comment]
Hi @GinaBiondo-aperto 
I tried to follow the conversation but I am not fully sure, what we need to adapt.
I listed the keyboard actions from the documentation and kindly ask you to confirm, what is requested.

**List Dropdown:**
- [ ] Down Arrow : Moves focus to the next option. 
- [ ] Up Arrow : Moves focus to the previous option. 

Multiple Selection: 
- [ ] Space : changes the selection state of the focused option 

**Checkbox:**
- [ ] Space:	Activates the checkbox

**Radiobutton:**
- [ ] Tab and Shift + Tab: Move focus into and out of the radiogroup. When focus moves into a radiogroup, if a radio button is checked, focus is set on the checked button. If none of the radio buttons are checked, focus is set on the first radio button in the group.
- [ ] Space: Checks the focused radio button if it is not already checked.
- [ ] Right Arrow and Down Arrow: Moves focus to the next radio button in the group, unchecking the previously focused button, and checking the newly focused button. If focus is on the last button, focus moves to the first button.
- [ ] Left Arrow and Up Arrow: Moves focus to the previous radio button in the group, unchecking the previously focused button, and checking the newly focused button. If focus is on the first button, focus moves to the last button.

I am having an additional qustion regarding the usage of the arrows. At the moment we are scrolling the page when using the up and down arrows. Will the current behaviour be obsolated or do I miss a something? 

Thank you for your feedback!
Magdalena

**Comment by carolabes** [comment]
Hi @mmarinkov, 

Your listed behaviors are correct. I would like to add something here:

Listbox (select):  
Focus state => If nothing is selected when opening this listbox, the first option is focused. If there are selected options, the first selected option is focused when opening.

Checkbox: 
No special behavior here. The user navigates with tab key and select with space.

To your question about scrolling behavior: Scrolling with up and down keys is still possible. It should only be disabled if I am in a list box or in a radio group. 
You can see the correct behavior in the examples of the native elements. 
Select does not scroll when the listbox is open because I can only operate the overlay and not the content below it: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select
With radio buttons, the page scrolls when I am in the first element and press the up key or in the last element and press the down key: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio

I hope I was able to answer your questions. If you have any further questions, please feel free to contact me.

Best regards,
Caro

**Comment by hirsch88** [comment]
Will be done it those issues

- #1446 
- #1447
